=== gentarap/Matkul-Sistem-Terdistribusi/PRAKTIKUM 5/Praktikum5_3_22SA11A116/Praktikum5_3_22SA11A116/mhs.dtd
<!ELEMENT data_mahasiswa (mahasiswa+)>
<!ELEMENT mahasiswa (nim,nama,prodi)>
<!ELEMENT nim (#PCDATA)>
<!ELEMENT nama (#PCDATA)>
<!ELEMENT prodi (#PCDATA)>

=== gentarap/Matkul-Sistem-Terdistribusi/PRAKTIKUM 5/Praktikum5_3_22SA11A116/Praktikum5_3_22SA11A116/Mahasiswa2.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE data_mahasiswa SYSTEM "mhs.dtd">
<data_mahasiswa>
	<mahasiswa>
		<nim>22SA11A116</nim>
		<nama>Gentar Jr</nama>
		<prodi>Pertambangan</prodi>
	</mahasiswa>

	<mahasiswa>
		<nim>22SA000222</nim>
		<nama>Sumbuls</nama>
		<prodi>Sistem Informasi</prodi>
	</mahasiswa>

	<mahasiswa>
		<nim>22SA000309</nim>
		<nama>Kuntaiman</nama>
		<prodi>Agroteknologi</prodi>
	</mahasiswa>
</data_mahasiswa>
